version: "3.8"
services:
  backend:
    build:
      context: ./be_ecommerce_phone
      dockerfile: Dockerfile
    container_name: phone-store-be
    ports:
      - "8080:8080"
    env_file:
      - ./be_ecommerce_phone/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./fe_ecommerce_phone
      dockerfile: Dockerfile
    container_name: phone-store-fe
    ports:
      - "3000:80"
    restart: unless-stopped
